# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5948f64162aa91719349423a33954ded17d545ca6d260af23ccd1671537c45c66237059bad5e72ad78c567e6361656cd8c03700915f37f9ee3c136bb426fbf5

test:
  secret_key_base: e207785ed837698c9155f3642024735a5b44da2c294dee3dfab5eeb095344d5c959e97fa44219a092509418c1ec28db8732194e50888b312463cad00ac133e24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
